name: plsc
dependencies:
    - python=3.7
    - pip
    - requests
    - ipython
    - jupyter
    - numpy=1.18.*
    - scipy==1.3.1
    - scikit-learn
    - opencv==3.4.2
    - pip:
        - paddlepaddle-gpu==1.8.5.post107
        - easydict